export const mockDemons = [
  {
    placement: "#1",
    name: "Bloodbath",
    creator: "Riot & more",
    id: "10565740",
    difficulty: "Extreme Demon",
    attempts: 20226,
    year: 2026,
    video: "Recorded",
    tier: 24.0,
    tierChange: 0,
    status: "COMPLETED",
    thumbnail: "",
    notes: "Current hardest demon."
  },
  {
    placement: "#2",
    name: "Make It Drop",
    creator: "ryamu & more",
    id: "75518661",
    difficulty: "Extreme Demon",
    attempts: 3137,
    year: 2025,
    video: "",
    tier: 20.57,
    tierChange: 0,
    status: "COMPLETED",
    thumbnail: "",
    notes: ""
  },
  {
    placement: "#3",
    name: "Acu",
    creator: "neigefeu",
    id: "61079355",
    difficulty: "Extreme Demon",
    attempts: 4575,
    year: 2023,
    video: "",
    tier: 20.25,
    tierChange: 0,
    status: "COMPLETED",
    thumbnail: "",
    notes: ""
  },
  {
    placement: "#4",
    name: "ICE Carbon Diablo X",
    creator: "roadbose",
    id: "814678",
    difficulty: "Insane Demon",
    attempts: 7159,
    year: 2024,
    video: "",
    tier: 19.78,
    tierChange: 0,
    status: "COMPLETED",
    thumbnail: "",
    notes: ""
  },
  {
    placement: "#5",
    name: "Beetle",
    creator: "Cirtrax",
    id: "61366260",
    difficulty: "Insane Demon",
    attempts: 1743,
    year: 2026,
    video: "",
    tier: 18.69,
    tierChange: 0.01,
    status: "COMPLETED",
    thumbnail: "",
    notes: "Recently beaten."
  }
];
